"""Add calculation_method to PrayerZoneCalendar

Revision ID: 1_add_calculation_method
Revises: 
Create Date: 2025-09-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1_add_calculation_method'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_zone_calendar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calculation_method', sa.String(length=50), nullable=False, server_default='default'))
        # First, drop the existing primary key constraint
        # Note: The actual name of the constraint might vary. 
        # We assume a default naming convention, but this might need adjustment if it fails.
        try:
            batch_op.drop_constraint('prayer_zone_calendar_pkey', type_='primary')
        except Exception as e:
            print(f"Could not drop constraint 'prayer_zone_calendar_pkey', it might not exist or have a different name. Error: {e}")

        # Now, create the new composite primary key
        batch_op.create_primary_key(
            'prayer_zone_calendar_pkey',
            ['zone_id', 'year', 'calculation_method']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prayer_zone_calendar', schema=None) as batch_op:
        # Drop the new composite primary key
        try:
            batch_op.drop_constraint('prayer_zone_calendar_pkey', type_='primary')
        except Exception as e:
            print(f"Could not drop constraint 'prayer_zone_calendar_pkey', it might not exist or have a different name. Error: {e}")

        # Recreate the old primary key
        batch_op.create_primary_key(
            'prayer_zone_calendar_pkey',
            ['zone_id', 'year']
        )
        
        batch_op.drop_column('calculation_method')

    # ### end Alembic commands ###
